name = "boann"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

main = "worker.ts"
assets = { directory = ".svelte-kit/cloudflare/", binding = "ASSETS" }

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "boann"
database_id = "fe23d201-b6ad-4077-949d-275ff2be582d"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "bc134c6752074c459622d7c32c360268"

[[r2_buckets]]
binding = "R2"
bucket_name = "boann"

[[queues.producers]]
binding = "QUEUE"
queue = "boann"

[[queues.consumers]]
queue = "boann"
max_batch_size = 10
max_retries = 3

[vars]
MOCK_AI = "false"
